# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170531_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='email_marketing',
            field=models.BooleanField(default=False, verbose_name='Email Marketing'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email_ok',
            field=models.BooleanField(default=False, verbose_name='Email confirmado'),
        ),
    ]
