# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170601_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='celular',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
